language: python
sudo: false

python:
  - "3.5"
  - "3.6"

install:
  - pip install codecov

script: 
  - nosetests --with-coverage

after_success:
  - codecov

# safelist
branches:
  only:
  - master
  - development
